Custom Auth Front
AirVantage/vleet pull request #5
Opened 2020-10-14 16:41 UTC by KINFOO

## Changes proposed

- Change formatting to [Prettier](https://prettier.io)
- A `authFrontServer` parameter to `setup.json`, a specific *Auth-Front* enables to create systems in an Airvantage running locally

## Smoke tests

<p align="center"><img src="https://media1.tenor.com/images/4771af1524f7ae443251af511525bf31/tenor.gif?itemid=11214428"/></p>

2020-10-14 17:34 UTC, KINFOO commented
I would like to add @asc-it as reviewer, looks like it is not possible for this project

2020-10-15 07:04 UTC, sebz commented
> I would like to add @asc-it as reviewer, looks like it is not possible for this project

Just added him as reviewer

2020-10-15 07:09 UTC, sebz requested changes
One minor remark. 
Also, your smoke test only test the new local version. Did you test it is still working with the prod servers?

2020-10-15 07:09 UTC, sebz commented on cli.js
> +    if (!!serverConfig.authFrontServer) {
Can't you use `const isLocal`?

2020-10-15 08:11 UTC, KINFOO commented
> One minor remark.
> Also, your smoke test only test the new local version. Did you test it is still working with the prod servers?

Just updated __smoke test__ section

2020-10-15 08:20 UTC, sebz approved these changes
LGTM

2020-10-15 08:41 UTC, asc-it approved these changes
LGTM
Vleet runs locally <3

2020-10-15 08:43 UTC, merged